# VuFind's default Lists group is inherited. The VuFind 11 Account group is
# reproduced here to use request terminology and add optional blank requests.
Account:
  label: Your Account
  id: acc-menu-acc-header
  class: account-menu
  MenuItems:
    - name: favorites
      label: saved_items
      route: myresearch-favorites
      icon: user-favorites
      checkMethod: checkFavorites

    - name: checkedout
      label: Checked Out Items
      route: myresearch-checkedout
      icon: user-checked-out
      status: true
      checkMethod: checkCheckedout

    - name: historicloans
      label: Request History
      route: checkouts-history
      icon: user-loan-history
      checkMethod: checkHistoricloans

    - name: holds
      label: My Requests
      route: holds-list
      icon: user-holds
      status: true
      checkMethod: checkHolds

    - name: storageRetrievalRequests
      label: Storage Retrieval Requests
      route: myresearch-storageretrievalrequests
      icon: user-storage-retrievals
      status: true
      checkMethod: checkStorageRetrievalRequests

    - name: ILLRequests
      label: Interlibrary Loan Requests
      route: myresearch-illrequests
      icon: user-ill-requests
      status: true
      checkMethod: checkILLRequests

    - name: fines
      label: Fines
      route: myresearch-fines
      status: true
      checkMethod: checkFines
      iconMethod: finesIcon

    - name: profile
      label: Profile
      route: myresearch-profile
      icon: profile

    - name: librarycards
      label: Library Cards
      route: librarycards-home
      icon: barcode
      checkMethod: checkLibraryCards

    - name: dgcontent
      label: Overdrive Content
      route: overdrive-mycontent
      icon: overdrive
      checkMethod: checkOverdrive

    - name: history
      label: Search History
      route: search-history
      icon: search
      checkMethod: checkHistory

    - name: usercontent
      label: user_content
      route: myresearch-usercontent
      icon: user-content
      checkMethod: checkUserContent

    - template: myresearch/menu-blank-requests.phtml

    - name: logout
      label: Log Out
      route: myresearch-logout
      icon: sign-out
      checkMethod: checkLogout
